### ISSUE TITLE
Support for Snapshot-Releases

### ISSUE THREAD

**Issue by maxfragg** [bokiscout/VivaldiThemeCreator#2]
since the path to the vivaldi-folder is hardcoded, this tool is unnecessarily limited to the vivaldi stable release. Could you add a dropdown, in case there are more subfolders in `$USER\AppData\Local\Vivaldi\Application` ?

**Comment by bokiscout** [comment]
You are right, one release of Vivaldi Theme Creator is limited to be used with exactly one version of Vivaldi.

Why I do it this way?
Vivaldi UI is still not mature, every next release has different nesting of the objects and names for those objects so a .css template designed for Vivaldi v1.0 is probably not fully compatible with Vivaldi v1.1. Since I can not guarantee that the provided .css template will work with multiple versions of Vivaldi I can not simply put a drop down menu for user to chose which version of Vivaldi is using.

My initial approach was to update Vivaldi Theme Creator with every release of Vivaldi and ensure that the templates are fully compatible but due to lack of time I skip a release from time to time.

Maybe better approach will be to add some kind of advanced mode (user will have to enable this mode manually) where user can type the version of Vivaldi by hand.

This way even if Vivaldi Theme Creator is not updated recently it might work just fine with latest release of Vivaldi Although I can not guarantee.

Anyway in next release I'll have to do something to enable better support for multiple releases.

**Comment by bokiscout** [comment]
Vivaldi Theme Creator 1.1.0 has support for snapshot releases but still it is best to be used against tested version of Vivaldi.
